# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- export LC_CTYPE=en_US.UTF-8

script:
- set -o pipefail && xcodebuild test -workspace Example/ITAhoCorasick-Demo.xcworkspace -scheme ITAhoCorasick-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination "platform=iOS Simulator,name=iPhone 5"| xcpretty -c
# - pod lib lint --quick
